-- Generated by: python3 analysis/patent_analysis.py --print-sql
-- Source of truth: analysis/patent_analysis.py (github.com/ignaciosim/AI4Chips_SLR)
-- Dataset: patents-public-data.patents.publications (BigQuery, public, free to query)
-- Publication-date window: 20150101-20261231

-- ========================================================================
-- patents_strict_list.csv
-- Strict AI-for-Chips list: chip/EDA CPC AND G06N CPC AND AI-method name in the title.
-- ========================================================================
WITH company_patterns AS (SELECT * FROM UNNEST([
    STRUCT('Intel' AS name, r'(?i)\bintel\b' AS pattern),
    STRUCT('NVIDIA' AS name, r'(?i)\bnvidia\b' AS pattern),
    STRUCT('Samsung' AS name, r'(?i)\bsamsung\b' AS pattern),
    STRUCT('TSMC' AS name, r'(?i)(\btsmc\b|taiwan semiconductor)' AS pattern),
    STRUCT('IBM' AS name, r'(?i)\b(ibm|international business machines)\b' AS pattern),
    STRUCT('Synopsys' AS name, r'(?i)\bsynopsys\b' AS pattern),
    STRUCT('Cadence' AS name, r'(?i)\bcadence\b' AS pattern),
    STRUCT('Siemens' AS name, r'(?i)\bsiemens\b' AS pattern),
    STRUCT('Mentor Graphics' AS name, r'(?i)mentor graphics' AS pattern),
    STRUCT('Google' AS name, r'(?i)(\bgoogle\b|alphabet)' AS pattern),
    STRUCT('Apple' AS name, r'(?i)\bapple\b' AS pattern),
    STRUCT('Meta' AS name, r'(?i)(meta platforms|\bfacebook\b)' AS pattern),
    STRUCT('Qualcomm' AS name, r'(?i)\bqualcomm\b' AS pattern),
    STRUCT('AMD' AS name, r'(?i)(\bamd\b|advanced micro devices)' AS pattern),
    STRUCT('ARM' AS name, r'(?i)\barm (ltd|limited|holdings)\b' AS pattern),
    STRUCT('Huawei' AS name, r'(?i)\bhuawei\b' AS pattern),
    STRUCT('MediaTek' AS name, r'(?i)mediatek' AS pattern),
    STRUCT('SK Hynix' AS name, r'(?i)(sk hynix|\bhynix\b)' AS pattern),
    STRUCT('Micron' AS name, r'(?i)\bmicron\b' AS pattern),
    STRUCT('STMicroelectronics' AS name, r'(?i)stmicroelectronics' AS pattern),
    STRUCT('Infineon' AS name, r'(?i)infineon' AS pattern),
    STRUCT('NXP' AS name, r'(?i)\bnxp\b' AS pattern),
    STRUCT('Broadcom' AS name, r'(?i)broadcom' AS pattern),
    STRUCT('Applied Materials' AS name, r'(?i)applied materials' AS pattern),
    STRUCT('KLA' AS name, r'(?i)(kla\-?tencor|\bkla\b)' AS pattern),
    STRUCT('Lam Research' AS name, r'(?i)lam research' AS pattern),
    STRUCT('ASML' AS name, r'(?i)\basml\b' AS pattern),
    STRUCT('imec' AS name, r'(?i)\bimec\b' AS pattern)
  ])),
    strict_ai_chip AS (
      SELECT
        p.family_id,
        p.publication_number,
        CAST(p.publication_date AS STRING) AS earliest_date,
        asg.name AS assignee_name,
        p.title_localized[SAFE_OFFSET(0)].text AS title,
        p.country_code,
        (SELECT STRING_AGG(c.code, ';') FROM UNNEST(p.cpc) c) AS cpc_codes
      FROM `patents-public-data.patents.publications` p,
      UNNEST(p.assignee_harmonized) asg
      WHERE p.publication_date BETWEEN 20150101 AND 20261231
        AND EXISTS(SELECT 1 FROM UNNEST(p.cpc) c WHERE c.code LIKE 'G06F30%' OR c.code LIKE 'G06F17/50%' OR c.code LIKE 'G06F115%' OR c.code LIKE 'G06F119%' OR c.code LIKE 'G06F11/22%' OR c.code LIKE 'G01R31/28%')
        AND EXISTS(SELECT 1 FROM UNNEST(p.cpc) c WHERE c.code LIKE 'G06N%')
        AND REGEXP_CONTAINS(
              LOWER(p.title_localized[SAFE_OFFSET(0)].text),
              r'(machine learning|artificial intelligence|\bai[- ]based\b|neural network|deep learning|reinforcement learning|graph neural|generative adversarial|\bgan[- ]|transformer[- ]based|large language model|\bllm[- ]|convolutional|recurrent neural|\bcnn[- ]|\brnn[- ]|\blstm\b|bayesian optimization|gaussian process|active learning|self-supervised|semi-supervised|variational autoencoder|\bvae\b|diffusion model)')
    ),
    first_per_family AS (
      SELECT
        cp.name AS matched_company,
        sac.family_id,
        ANY_VALUE(sac.publication_number) AS publication_number,
        MIN(sac.earliest_date) AS earliest_date,
        ANY_VALUE(sac.assignee_name) AS assignee,
        ANY_VALUE(sac.title) AS title,
        ANY_VALUE(sac.country_code) AS country_code,
        ANY_VALUE(sac.cpc_codes) AS cpc_codes
      FROM company_patterns cp
      JOIN strict_ai_chip sac
        ON REGEXP_CONTAINS(sac.assignee_name, cp.pattern)
      GROUP BY cp.name, sac.family_id
    )
    SELECT * FROM first_per_family
    ORDER BY matched_company, earliest_date DESC
;

-- ========================================================================
-- patents_strict_list_chipkw_sensitivity.csv
-- Sensitivity cut: same CPC conjunction, chip-domain keyword in the title instead of an AI-method name. Rows whose title also matches
-- r'(battery|flood|drug|medical|genomic|pharmaceutical|autonomous vehicle|autonomous drivin|traffic simulation|traffic flow|robot(?!ic)|robotic)'
-- are dropped in pandas after the query returns, not in SQL.
-- ========================================================================
WITH company_patterns AS (SELECT * FROM UNNEST([
    STRUCT('Intel' AS name, r'(?i)\bintel\b' AS pattern),
    STRUCT('NVIDIA' AS name, r'(?i)\bnvidia\b' AS pattern),
    STRUCT('Samsung' AS name, r'(?i)\bsamsung\b' AS pattern),
    STRUCT('TSMC' AS name, r'(?i)(\btsmc\b|taiwan semiconductor)' AS pattern),
    STRUCT('IBM' AS name, r'(?i)\b(ibm|international business machines)\b' AS pattern),
    STRUCT('Synopsys' AS name, r'(?i)\bsynopsys\b' AS pattern),
    STRUCT('Cadence' AS name, r'(?i)\bcadence\b' AS pattern),
    STRUCT('Siemens' AS name, r'(?i)\bsiemens\b' AS pattern),
    STRUCT('Mentor Graphics' AS name, r'(?i)mentor graphics' AS pattern),
    STRUCT('Google' AS name, r'(?i)(\bgoogle\b|alphabet)' AS pattern),
    STRUCT('Apple' AS name, r'(?i)\bapple\b' AS pattern),
    STRUCT('Meta' AS name, r'(?i)(meta platforms|\bfacebook\b)' AS pattern),
    STRUCT('Qualcomm' AS name, r'(?i)\bqualcomm\b' AS pattern),
    STRUCT('AMD' AS name, r'(?i)(\bamd\b|advanced micro devices)' AS pattern),
    STRUCT('ARM' AS name, r'(?i)\barm (ltd|limited|holdings)\b' AS pattern),
    STRUCT('Huawei' AS name, r'(?i)\bhuawei\b' AS pattern),
    STRUCT('MediaTek' AS name, r'(?i)mediatek' AS pattern),
    STRUCT('SK Hynix' AS name, r'(?i)(sk hynix|\bhynix\b)' AS pattern),
    STRUCT('Micron' AS name, r'(?i)\bmicron\b' AS pattern),
    STRUCT('STMicroelectronics' AS name, r'(?i)stmicroelectronics' AS pattern),
    STRUCT('Infineon' AS name, r'(?i)infineon' AS pattern),
    STRUCT('NXP' AS name, r'(?i)\bnxp\b' AS pattern),
    STRUCT('Broadcom' AS name, r'(?i)broadcom' AS pattern),
    STRUCT('Applied Materials' AS name, r'(?i)applied materials' AS pattern),
    STRUCT('KLA' AS name, r'(?i)(kla\-?tencor|\bkla\b)' AS pattern),
    STRUCT('Lam Research' AS name, r'(?i)lam research' AS pattern),
    STRUCT('ASML' AS name, r'(?i)\basml\b' AS pattern),
    STRUCT('imec' AS name, r'(?i)\bimec\b' AS pattern)
  ])),
    strict_ai_chip AS (
      SELECT
        p.family_id,
        p.publication_number,
        CAST(p.publication_date AS STRING) AS earliest_date,
        asg.name AS assignee_name,
        p.title_localized[SAFE_OFFSET(0)].text AS title,
        p.country_code,
        (SELECT STRING_AGG(c.code, ';') FROM UNNEST(p.cpc) c) AS cpc_codes
      FROM `patents-public-data.patents.publications` p,
      UNNEST(p.assignee_harmonized) asg
      WHERE p.publication_date BETWEEN 20150101 AND 20261231
        AND EXISTS(SELECT 1 FROM UNNEST(p.cpc) c WHERE c.code LIKE 'G06F30%' OR c.code LIKE 'G06F17/50%' OR c.code LIKE 'G06F115%' OR c.code LIKE 'G06F119%' OR c.code LIKE 'G06F11/22%' OR c.code LIKE 'G01R31/28%')
        AND EXISTS(SELECT 1 FROM UNNEST(p.cpc) c WHERE c.code LIKE 'G06N%')
        AND REGEXP_CONTAINS(
              LOWER(p.title_localized[SAFE_OFFSET(0)].text),
              r'(integrated circuit|semiconductor|wafer|die|transistor|mosfet|finfet|cmos|ic design|chip design|chiplet|layout|placement|routing|floorplan|synthesis|lithograph|mask|opc|optical proximity|inverse lithograph|metrology|yield|defect|rtl|verilog|vhdl|netlist|hdl|timing|\bic\b|eda|power grid|power delivery|pdn|ir drop|clock tree|trojan|fab|fabric|scatterometry|post-silicon|silicon|imaging system|overlay|bump)')
    ),
    first_per_family AS (
      SELECT
        cp.name AS matched_company,
        sac.family_id,
        ANY_VALUE(sac.publication_number) AS publication_number,
        MIN(sac.earliest_date) AS earliest_date,
        ANY_VALUE(sac.assignee_name) AS assignee,
        ANY_VALUE(sac.title) AS title,
        ANY_VALUE(sac.country_code) AS country_code,
        ANY_VALUE(sac.cpc_codes) AS cpc_codes
      FROM company_patterns cp
      JOIN strict_ai_chip sac
        ON REGEXP_CONTAINS(sac.assignee_name, cp.pattern)
      GROUP BY cp.name, sac.family_id
    )
    SELECT * FROM first_per_family
    ORDER BY matched_company, earliest_date DESC
;

-- ========================================================================
-- patents_vs_publications.csv
-- Loose OR-based CPC count. Magnitude reference only; not reported as a headline number.
-- ========================================================================
WITH company_patterns AS (SELECT * FROM UNNEST([
    STRUCT('Intel' AS name, r'(?i)\bintel\b' AS pattern),
    STRUCT('NVIDIA' AS name, r'(?i)\bnvidia\b' AS pattern),
    STRUCT('Samsung' AS name, r'(?i)\bsamsung\b' AS pattern),
    STRUCT('TSMC' AS name, r'(?i)(\btsmc\b|taiwan semiconductor)' AS pattern),
    STRUCT('IBM' AS name, r'(?i)\b(ibm|international business machines)\b' AS pattern),
    STRUCT('Synopsys' AS name, r'(?i)\bsynopsys\b' AS pattern),
    STRUCT('Cadence' AS name, r'(?i)\bcadence\b' AS pattern),
    STRUCT('Siemens' AS name, r'(?i)\bsiemens\b' AS pattern),
    STRUCT('Mentor Graphics' AS name, r'(?i)mentor graphics' AS pattern),
    STRUCT('Google' AS name, r'(?i)(\bgoogle\b|alphabet)' AS pattern),
    STRUCT('Apple' AS name, r'(?i)\bapple\b' AS pattern),
    STRUCT('Meta' AS name, r'(?i)(meta platforms|\bfacebook\b)' AS pattern),
    STRUCT('Qualcomm' AS name, r'(?i)\bqualcomm\b' AS pattern),
    STRUCT('AMD' AS name, r'(?i)(\bamd\b|advanced micro devices)' AS pattern),
    STRUCT('ARM' AS name, r'(?i)\barm (ltd|limited|holdings)\b' AS pattern),
    STRUCT('Huawei' AS name, r'(?i)\bhuawei\b' AS pattern),
    STRUCT('MediaTek' AS name, r'(?i)mediatek' AS pattern),
    STRUCT('SK Hynix' AS name, r'(?i)(sk hynix|\bhynix\b)' AS pattern),
    STRUCT('Micron' AS name, r'(?i)\bmicron\b' AS pattern),
    STRUCT('STMicroelectronics' AS name, r'(?i)stmicroelectronics' AS pattern),
    STRUCT('Infineon' AS name, r'(?i)infineon' AS pattern),
    STRUCT('NXP' AS name, r'(?i)\bnxp\b' AS pattern),
    STRUCT('Broadcom' AS name, r'(?i)broadcom' AS pattern),
    STRUCT('Applied Materials' AS name, r'(?i)applied materials' AS pattern),
    STRUCT('KLA' AS name, r'(?i)(kla\-?tencor|\bkla\b)' AS pattern),
    STRUCT('Lam Research' AS name, r'(?i)lam research' AS pattern),
    STRUCT('ASML' AS name, r'(?i)\basml\b' AS pattern),
    STRUCT('imec' AS name, r'(?i)\bimec\b' AS pattern)
  ])),
    loose_ai_chip AS (
      SELECT p.family_id, asg.name AS assignee_name
      FROM `patents-public-data.patents.publications` p,
      UNNEST(p.assignee_harmonized) asg
      WHERE p.publication_date BETWEEN 20150101 AND 20261231
        AND EXISTS(SELECT 1 FROM UNNEST(p.cpc) c
                   WHERE c.code LIKE 'G06F30%' OR c.code LIKE 'G06F17/50%'
                      OR c.code LIKE 'G06N3%'   OR c.code LIKE 'G06F115%'
                      OR c.code LIKE 'G06F119%' OR c.code LIKE 'G06F11/22%'
                      OR c.code LIKE 'G01R31/28%')
    )
    SELECT cp.name AS company,
           COUNT(DISTINCT lac.family_id) AS loose_patent_families
    FROM company_patterns cp
    JOIN loose_ai_chip lac ON REGEXP_CONTAINS(lac.assignee_name, cp.pattern)
    GROUP BY company
    ORDER BY loose_patent_families DESC
;

-- ========================================================================
-- case_study_patents.csv
-- Case-study probe for DREAMPlace (Lin 2021) (DOI 10.1109/tcad.2020.3003843).
-- ========================================================================
SELECT
          'DREAMPlace (Lin 2021)' AS paper,
          '10.1109/tcad.2020.3003843' AS paper_doi,
          p.publication_number,
          p.family_id,
          EXTRACT(YEAR FROM PARSE_DATE('%Y%m%d', CAST(p.publication_date AS STRING))) AS pub_year,
          p.title_localized[SAFE_OFFSET(0)].text AS title,
          ARRAY(SELECT x.name FROM UNNEST(p.assignee_harmonized) x) AS assignees,
          ARRAY(SELECT x FROM UNNEST(p.inventor) x) AS inventors,
          p.country_code
        FROM `patents-public-data.patents.publications` p
        WHERE p.publication_date BETWEEN 20170101 AND 20281231
          AND EXISTS(SELECT 1 FROM UNNEST(p.inventor) i
                     WHERE REGEXP_CONTAINS(LOWER(i), r'(?i)(yibo lin|haoxing ren|khailany)'))
          AND REGEXP_CONTAINS(LOWER(p.title_localized[SAFE_OFFSET(0)].text),
                              r'(?i)(placement|floorplan|routing|layout.*gpu|layout.*neural|crosstalk|accelerat)')
          AND EXISTS(SELECT 1 FROM UNNEST(p.cpc) c
                     WHERE c.code LIKE 'G06F30%' OR c.code LIKE 'G06F17/50%'
                        OR c.code LIKE 'G06N3%'  OR c.code LIKE 'G06F115%'
                        OR c.code LIKE 'H01L%')
        ORDER BY p.publication_date DESC
        LIMIT 30
;

-- ========================================================================
-- case_study_patents.csv
-- Case-study probe for VeriGen (Thakur 2024) (DOI 10.1145/3643681).
-- ========================================================================
SELECT
          'VeriGen (Thakur 2024)' AS paper,
          '10.1145/3643681' AS paper_doi,
          p.publication_number,
          p.family_id,
          EXTRACT(YEAR FROM PARSE_DATE('%Y%m%d', CAST(p.publication_date AS STRING))) AS pub_year,
          p.title_localized[SAFE_OFFSET(0)].text AS title,
          ARRAY(SELECT x.name FROM UNNEST(p.assignee_harmonized) x) AS assignees,
          ARRAY(SELECT x FROM UNNEST(p.inventor) x) AS inventors,
          p.country_code
        FROM `patents-public-data.patents.publications` p
        WHERE p.publication_date BETWEEN 20200101 AND 20281231
          AND EXISTS(SELECT 1 FROM UNNEST(p.inventor) i
                     WHERE REGEXP_CONTAINS(LOWER(i), r'(?i)(shailja thakur|ramesh karri|siddharth garg|hammond pearce)'))
          AND REGEXP_CONTAINS(LOWER(p.title_localized[SAFE_OFFSET(0)].text),
                              r'(?i)(verilog|rtl|hdl|language model|code generation|trojan|hardware security)')
          AND EXISTS(SELECT 1 FROM UNNEST(p.cpc) c
                     WHERE c.code LIKE 'G06F30%' OR c.code LIKE 'G06F17/50%'
                        OR c.code LIKE 'G06N3%'  OR c.code LIKE 'G06F115%'
                        OR c.code LIKE 'H01L%')
        ORDER BY p.publication_date DESC
        LIMIT 30
;

-- ========================================================================
-- case_study_patents.csv
-- Case-study probe for GAN-OPC (Yang 2020) (DOI 10.1109/tcad.2019.2939329).
-- ========================================================================
SELECT
          'GAN-OPC (Yang 2020)' AS paper,
          '10.1109/tcad.2019.2939329' AS paper_doi,
          p.publication_number,
          p.family_id,
          EXTRACT(YEAR FROM PARSE_DATE('%Y%m%d', CAST(p.publication_date AS STRING))) AS pub_year,
          p.title_localized[SAFE_OFFSET(0)].text AS title,
          ARRAY(SELECT x.name FROM UNNEST(p.assignee_harmonized) x) AS assignees,
          ARRAY(SELECT x FROM UNNEST(p.inventor) x) AS inventors,
          p.country_code
        FROM `patents-public-data.patents.publications` p
        WHERE p.publication_date BETWEEN 20180101 AND 20281231
          AND EXISTS(SELECT 1 FROM UNNEST(p.inventor) i
                     WHERE REGEXP_CONTAINS(LOWER(i), r'(?i)(haoyu yang|bei yu)'))
          AND REGEXP_CONTAINS(LOWER(p.title_localized[SAFE_OFFSET(0)].text),
                              r'(?i)(mask|opc|optical proximity|lithograph|layout pattern|hotspot)')
          AND EXISTS(SELECT 1 FROM UNNEST(p.cpc) c
                     WHERE c.code LIKE 'G06F30%' OR c.code LIKE 'G06F17/50%'
                        OR c.code LIKE 'G06N3%'  OR c.code LIKE 'G06F115%'
                        OR c.code LIKE 'H01L%')
        ORDER BY p.publication_date DESC
        LIMIT 30
;
